version: '3'
volumes:
  # vendorファイルをgitから取り除き、ローカルに入れないために
  # volumeから除外することで対応している。
  exclude_vendor_from_phpfpm_volume:
services:
  dynamodb:
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    expose:
      - "58001"
    ports:
      - "8000:8000"
    hostname: dynamodb
    container_name: dynamodb
    volumes:
      - ./dynamodb/data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -dbPath ./data
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "50080:80"
    links:
      - phpfpm
    depends_on:
      - phpfpm
  phpfpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./laravel:/var/www/
      - exclude_vendor_from_phpfpm_volume:/var/www/vendor
    env_file: ./laravel/.env
  dynamodbadmin:
    image: instructure/dynamo-local-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000/
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
      AWS_DEFAULT_REGION: localhost:8000
      AWS_REGION: localhost:8000
